### ISSUE TITLE
兄弟

### ISSUE THREAD

**Issue by ChenHongBo0420** [ZhenyueQin/Angular-Skeleton-Encoding#2]
都快2022年了 这个项目我盯了半年了

**Comment by ZhenyueQin** [comment]
Hi, please check this file: https://github.com/ZhenyueQin/Angular-Skeleton-Encoding/blob/main/generate_ntu_angular_encoding.py. This contains the script that we used for generating the angular encoding.

**Comment by ChenHongBo0420** [comment]
thanks a lot.I mean no more training and path?

**Comment by ZhenyueQin** [comment]
The encoding is compatible with other models for skeleton-based action recognition. You may process the original data with the script.

**Comment by ChenHongBo0420** [comment]
I see. thanks a lot ！！

**Comment by LeiJiang1** [comment]
Could you share the generate_ntu_angular_encoding.py. I can't find anything through the link you give. Thanks
